### ISSUE TITLE
not working with TB 62.0a1 (2018-05-28) (64-bit)

### ISSUE THREAD

**Issue by ghost** [BobSoft3000/tb-sensitivity-header#2]
WIN 10 1709 b16299.461
TB 62.0a1 (2018-05-28) (64-bit)
tb-s-h 0.2

From the Options drop down tb-s-h is a now show.

**Comment by BobSoft3000** [comment]
Thanks for letting me know - just tested this on TB 'Daily' (2018-05-28) (Win7-64) and can confirm my addon (and several others I use) don't work any more.
I also tested on TB 60.0b6 and current stable version (52.8.0) and the addon worked on those.
It looks like the thunderbird devs changed how addons work past TB60 (current 'Beta') so this is going to need quite a few code changes.  Seems like a side-effect of Firefox dropping 'legacy' addons in favour of web extensions, and TB devs simplifying things.
Still trying to find some conclusive documents identifying what is supposed to change, how, and when.

**Comment by BobSoft3000** [comment]
As far as I can tell 0.2 should still work on the stable thunderbird branch, and 0.3 should now work on the beta.

**Comment by n8v8R** [comment]
this been
