### ISSUE TITLE
incompatible with TB69 (beta)

### ISSUE THREAD

**Issue by ghost** [BobSoft3000/tb-sensitivity-header#4]
- Operating System: W10 Pro x_64 v1903 b18362.267
- Thunderbird: 69.0b1 (64-bit)
- SH: 0.2
_____
![Annotation 2019-07-29 165313](https://user-images.githubusercontent.com/13611490/62063779-d77ad500-b22b-11e9-9c07-9a28330150b9.png)

**Comment by BobSoft3000** [comment]
Version 0.3 uploaded to https://addons.thunderbird.net/ ... /thunderbird/addon/sensitivity-header/ has just been approved.   I didn't change the underlying code - just included manifest.json and removed install.rdf from the package.

**Comment by ghost** [comment]
Thank you, works now
